### ISSUE TITLE
Duplicated reference to a chapter

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization#15]
on https://docs.typo3.org/typo3cms/FrontendLocalizationGuide/latest/TyposcriptConfiguration/

```
The config.sys_language_mode and config.sys_language_overlay 
properties are described more in detail in the 
Localization modes chapter and the Localization modes chapter respectively.
```

the "Localization modes chapter" is mentioned twice with the same link.

**Comment by marble** [comment]
Yes, looks irritating. To be precise: links are different, but linktexts are the same.

**Comment by Chrissitopher** [comment]
Thanks for noting this issue! I just fixed it.
