### ISSUE TITLE
Update FrontendLocalization guide to 10.4

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization#34]
https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/SettingUpLanguages/Index.html

- sys_language records are outdated. Change to explanation on how to update the site configuration. (link to site configuration documentation)

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizationOverview/Index.html
- Update the screenshots: Buttons in Languages module changed slightly, the language related checkboxes in page editing are now located in the Languages tab.
- The last paragraphs mention some outdated typoscript settings (like config.sys_language_mode). Switch these explanations out with their site configuration counter parts (and a link to the language section of the site config documentation)

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/TyposcriptConfiguration/Index.html
- Completely outdated for 10.4. Remove everything? Could probably directly link to the language section of the site config documentation.

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizationModes/Index.html
- Same here. Could be completely rewritten. Change all the config.sys_language_mode parts with their site configuration counter part. 
- The whole comparison table is outdated. New behaviour: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/AddLanguages.html

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizedLabels/Index.html
- Several mentions of "config.language", which no longer exists -> site configuration

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LanguageMenu/Index.html
- The whole TMENU example could be simplified. For instance, since 9.5 there is a "language" option for typolink. 
- GMENU no longer exists and should be completely removed.

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizedContent/Index.html
- Mentions of several config.sys_language_* -> change to site config counter parts.

https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/CoreSupport/Tca/Index.html
- TCA example code for "sys_language_uid" and "l18n_parent" are outdated. As an example what it should look like, look up ext:core/Configuration/TCA/sys_category.php
- Mention of config.sys_language_overlay

**Comment by IndyIndyIndy** [comment]
After the changes, search the project for remaining occurrences of config.sys_language_*, config.language*

**Comment by susannemoog** [comment]
PR is merged, thanks!
