### ISSUE TITLE
Add missing doc in "Setting up languages" for 10.4

### ISSUE THREAD

**Issue by CeliaCha** [TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization#40]
I wonder why the documentation part "The system languages are added on the root level of the page tree" with illustrated exemples, which is present in the 9.5 doc, is missing in the 10.4. I think it's an important part in the step by step localization process.

**Comment by brotkrueml** [comment]
This is now outdated as the system languages (table "sys_language") is deprecated in v11 and removed in upcoming v12: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html

**Comment by DavidBruchmann** [comment]
might it be  useful to add a depreciation notice to the documentation?

**Comment by brotkrueml** [comment]
@DavidBruchmann Feel free to add it.

**Comment by DavidBruchmann** [comment]
@CeliaCha thanks for reporting!
